<?php
/**
 * GetDeliveryFloorModelPostModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenNachonUtils
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen Utils for Nachon
 *
 * SayWhen Utils for Nachon API Documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SayWhenNachonUtils;

/**
 * GetDeliveryFloorModelPostModelTest Class Doc Comment
 *
 * @category    Class */
// * @description GetDeliveryFloorModelPostModel
/**
 * @package     SayWhenNachonUtils
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDeliveryFloorModelPostModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetDeliveryFloorModelPostModel"
     */
    public function testGetDeliveryFloorModelPostModel()
    {
    }

    /**
     * Test attribute "bop_id"
     */
    public function testPropertyBopId()
    {
    }

    /**
     * Test attribute "question_and_answers"
     */
    public function testPropertyQuestionAndAnswers()
    {
    }
}
