<?php
/**
 * UtilsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenNachonUtils
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen Utils for Nachon
 *
 * SayWhen Utils for Nachon API Documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SayWhenNachonUtils;

use \SayWhenNachonUtils\Configuration;
use \SayWhenNachonUtils\ApiClient;
use \SayWhenNachonUtils\ApiException;
use \SayWhenNachonUtils\ObjectSerializer;

/**
 * UtilsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SayWhenNachonUtils
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UtilsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDeliveryFloor
     *
     * GetDeliveryFloor from SurveyResults.
     *
     */
    public function testGetDeliveryFloor()
    {
    }
}
